Update export_release.yml

diff --git a/.github/workflows/export_release.yml b/.github/workflows/export_release.yml
--- a/.github/workflows/export_release.yml
+++ b/.github/workflows/export_release.yml
@@ -4,10 +4,10 @@ on:
   workflow_dispatch:
     inputs:
       version_name:
-        description: 'Version name (e.g., 0.10.9)'
+        description: 'Version name (e.g., 0.12.2)'
         required: true
       version_code:
-        description: 'Version code (e.g., 100082)'
+        description: 'Version code (e.g., 100130)'
         required: true
       upload_to_itch:
         description: 'Upload exported files to itch.io?'
@@ -38,8 +38,8 @@ jobs:
       - name: Validate Version in Changelog
         run: |
           if ! grep -q "## v${{ inputs.version_name }}" CHANGELOG.md; then
-            echo "Error: Version ${{ inputs.version_name }} not found in CHANGELOG.md"
-            exit 1
+          echo "Error: Version ${{ inputs.version_name }} not found in CHANGELOG.md"
+          exit 1
           fi
 
       - name: Check Existing Version Code
@@ -55,15 +55,43 @@ jobs:
           sed -n "/## v${{ inputs.version_name }}/,/## v/p" CHANGELOG.md | \
           sed '$d' | sed '1s/^## //' > \
           "./fastlane/metadata/android/en-US/changelogs/${{ inputs.version_code }}.txt"
-
-      - name: Update Version Info
+          
+      - name: Get Previous Version Code
+        id: prev_version
         run: |
-          sed -i "/version\/name=\".*\"/s//version\/name=\"${{ inputs.version_name }}\"/" export_presets.cfg
-          sed -i "0,/version\/code=[0-9]*/s//version\/code=${{ inputs.version_code }}/" export_presets.cfg
-          sed -i "0,/version\/code=[0-9]*/! s/version\/code=[0-9]*/version\/code=$((VERSION_CODE+1))/" export_presets.cfg
+          PREV_CODE=$(grep -o 'version/code=[0-9]*' export_presets.cfg | head -1 | cut -d= -f2)
+          NEW_CODE=$((PREV_CODE + 10))
+          echo "prev_code=${PREV_CODE}" >> $GITHUB_OUTPUT
+          echo "new_code=${NEW_CODE}" >> $GITHUB_OUTPUT
+      
+      - name: Commit Previous Version Code
+        run: |
+          echo "Previous version code: ${{ steps.prev_version.outputs.prev_code }}"
+          echo "New version code: ${{ steps.prev_version.outputs.new_code }}"
+          
+          VERSION_CODE=${{ steps.prev_version.outputs.new_code }}
+          
+          # Update version codes
+          sed -i "0,/version\/code=[0-9]*/s//version\/code=$VERSION_CODE/" export_presets.cfg
+          sed -i "0,/version\/code=[0-9]*/! {0,/version\/code=[0-9]*/s//version\/code=$((VERSION_CODE+1))/}" export_presets.cfg
           sed -i "$(grep -n 'version/code=' export_presets.cfg | tail -n1 | cut -d: -f1),\$s/version\/code=[0-9]*/version\/code=$((VERSION_CODE+2))/" export_presets.cfg
-        env:
-          VERSION_CODE: ${{ inputs.version_code }}
+
+      - name: Commit Changes
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add export_presets.cfg
+          git add ./fastlane/metadata/android/en-US/changelogs/${{ inputs.version_code }}.txt
+          git commit -m "Update version to ${{ inputs.version_name }} (${{ inputs.version_code }})"
+          git push
+      # - name: Update Version Info
+      #   run: |
+      #     sed -i "/version\/name=\".*\"/s//version\/name=\"${{ inputs.version_name }}\"/" export_presets.cfg
+      #     sed -i "0,/version\/code=[0-9]*/s//version\/code=${{ inputs.version_code }}/" export_presets.cfg
+      #     sed -i "0,/version\/code=[0-9]*/! s/version\/code=[0-9]*/version\/code=$((VERSION_CODE+1))/" export_presets.cfg
+      #     sed -i "$(grep -n 'version/code=' export_presets.cfg | tail -n1 | cut -d: -f1),\$s/version\/code=[0-9]*/version\/code=$((VERSION_CODE+2))/" export_presets.cfg
+      #   env:
+      #     VERSION_CODE: ${{ inputs.version_code }}
           
       - name: Build
         uses: mlm-games/godot-build-action@main
@@ -100,12 +128,3 @@ jobs:
           body_path: ./fastlane/metadata/android/en-US/changelogs/${{ inputs.version_code }}.txt
           prerelease: ${{ inputs.mark_prerelease }}
           generate_release_notes: true
-
-      - name: Commit Changes
-        run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add export_presets.cfg
-          git add ./fastlane/metadata/android/en-US/changelogs/${{ inputs.version_code }}.txt
-          git commit -m "Update version to ${{ inputs.version_name }} (${{ inputs.version_code }})"
-          git push
